### ISSUE TITLE
Create a Node class

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#113]
As a developer, I want to be able to use a node class containing coordinates, so that I can easily plot their locations and use them to create a canvas image.

## Definition of Done
- [x] #121 
- [x] #122 
- [x] #123 
- [x] #124

**Comment by mariotorres1** [comment]
Took me about a day to do all the work for this story make sure the linter was happy

**Comment by mariotorres1** [comment]
My actual task work took about 2.5 hours to complete and a more detailed description of that time is in the actual task issues. I did work more on making the linter happy but that was mainly fixing indentation.
