### ISSUE TITLE
Add pressures to Heat Map key

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#155]
As a user, I want to see a range of pressures from the data I uploaded corresponding to specific colors, so that I can have an accurate visualization of the pressure values for that data on the heat map.

## Definition of Done
- [x] Pressure values appear in heat map key
- [x] Pressure values can be changed based on different ranges from .results files?

Note: Will need to ask sponsor more about how these values should act and be displayed before starting work. Story may need editing.

## Tasks
- [x] #226 
- [x] #227

**Comment by shuai-yang** [comment]
Thursday, October 27th 2PM - 3PM(1 hour):
During the checkout meeting with sponsor, I asked the below questions and here are her new requirements for this functionality. 

How many colors do we need? 
at least, 7 or 8

Are there specific colors we should use?  
same scale
Red-blue scheme - mentioned “Jet colorscheme” from Matlab

What units will the pressure ranges be in?
Mega pascals for pressures.  No units for strain - strain can be positive or negative

Do the pressure ranges associated with each color change based on the results files(meaning equally allocate the range to each color), or are the ranges always the same?
Shows the mean, max principle ( min principle are negative values 0 is the blue value, largest neg to be red)
Dynamic max and min
Strain can be positive or negative - 0 should always be blue, greatest difference from 0 should be red
Min for pressure can always be 0

**Comment by shuai-yang** [comment]
Follow up with sponsor if data files are not received by Monday, October 31st.

**Comment by shuai-yang** [comment]
Received email back from Vahid with additional two subjects but for the contact pressure data, he said he couldn't export CPRESS with the same format that I'm sending S and LE in, so he'll do some work and send it as soon as it is ready.

**Comment by shuai-yang** [comment]
By now, the sample data I used are from  9993833M00_Results/CART-PATELLA_LE.csv

Note: "The LE.results file contains Max Principal Strain, and S.results contains Mises Stress"
