### ISSUE TITLE
Update 'Upload' button into functional 'Draw' button

### ISSUE THREAD

**Issue by shuai-yang** [cs481-ekh/f22-kneed-for-speed#161]
As a developer, I want to develop a 'Draw' button. So once the button is clicked, the image will be drawn.

## Definition of Done
- [ ] Criterion 1
- [ ] Criterion 2

## Tasks
- [ ] Task 1
- [ ] Task 2

**Comment by katerosenthal** [comment]
Story already exists elsewhere, #154. Closing this duplicate.
