### ISSUE TITLE
Add content to README file

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#211]
As a developer, I want to have an informative and descriptive README file, so that I can be sure that potential users and future collaborators can easily use and understand my project.

## Definition of Done
- [ ] README accurately describes project
- [ ] README includes at least the project name, team members, abstract, and project description

## Tasks
- [ ] Task 1
- [ ] Task 2

**Comment by shuai-yang** [comment]
Here's the requirements


![Image](https://user-images.githubusercontent.com/5439644/202024765-797ed64c-9687-4014-ac52-99a499edb79b.png)

**Comment by shuai-yang** [comment]
PR pushed. Still need to update it time to time with the new updates after this Sprint.
