### ISSUE TITLE
Test uploading files to main page

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#29]
As a developer, I want to ensure that files are uploading to my page correctly, so that I can produce a fully functioning product for my users.

## Definition of Done
- [ ] Tests written or method well documented
- [ ] Test results are consistent and repeatable

**Comment by shuai-yang** [comment]
Question: Since the uploaded document is not saved on Server, I am not sure how to test the uploaded file is stored. Will ask this question in next team meeting and move forward to implement the test task.

**Comment by katerosenthal** [comment]
I think we talked about maybe looking into storing it as session data, but some more research needed to be done. Here is hopefully a good place to start:

https://www.javascripttutorial.net/web-apis/javascript-sessionstorage/
https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

**Comment by shuai-yang** [comment]
I've manually test the parser using .inp, .txt. and .csv file. and makes sure it works for all of these classical text file types.

**Comment by katerosenthal** [comment]
This can be closed, but more testing will need to be done after all upload functionality is completed in #152 and #151 where it was moved to. We can create our own tasks for that, though.
