### ISSUE TITLE
Practice Plotting Geometrics

### ISSUE THREAD

**Issue by BSU-EzekielHolmes** [cs481-ekh/f22-kneed-for-speed#81]
As a developer, I want to make sure I'm able to add heat map elements to the canvas based on dummy files provided through user input, so that I can ensure the plot points are accurate when using the real data.

## Definition of Done
- [x] Figure out if we can change 0,0 position on canvas to middle instead of top left
- [x] #93 
- [x] #94 
- [x] #95

**Comment by mariotorres1** [comment]
Here's a good discussion on stackoverflow, showing how to move the 0, 0 position on the canvas. https://stackoverflow.com/questions/29742350/write-0-0-in-center-of-the-canvas-html5

**Comment by mariotorres1** [comment]
Started a little late on story, researched and practiced how to move the 0, 0 position for about a day.

**Comment by mariotorres1** [comment]
Once I started on the tasks that required code implementation, it took me about 2 hours to complete the tasks for this story
