### ISSUE TITLE
Implement Heat Map Key

### ISSUE THREAD

**Issue by BSU-EzekielHolmes** [cs481-ekh/f22-kneed-for-speed#84]
As a developer, I want to add a scale to our heat map, so that end-users have a frame of reference when viewing the visual output on our canvas.

## Definition of Done
- [x] Figure out if we want to use picture of different heat map colors. (Already on our web page)
- [x] #118 
- [x] #119 
- [x] #120

**Comment by mariotorres1** [comment]
probably going to have to create a function to do this work

**Comment by mariotorres1** [comment]
This is the best example I could find researching: https://stackoverflow.com/questions/36556309/create-legend-in-javascript

**Comment by mariotorres1** [comment]
I think the values are going to have to be dynamic based on the data we are reading as well, that can't be done until the parsing is complete

**Comment by mariotorres1** [comment]
This issue is going to have to be pushed into sprint 3 where we can hopefully have a better understanding of how many colors we're going to use. We also need to figure out how we are going to choose which data value corresponds to each color.

**Comment by mariotorres1** [comment]
Looking at other functions that create a legend/key online, it doesn't seem like it will be too difficult to implement once we have the above questions answered.

**Comment by mariotorres1** [comment]
This story took me about 3.5-4 hours in total over a couple of days. There is a more detailed description on how long each task took in those actually issues.
